### ISSUE TITLE
Copy paste date in date range picker throws console errors

### ISSUE THREAD

**Issue by rashmimundgod** [predixdesignsystem/px-rangepicker#23]
Environment - https://stuf-rc.run.asv-pr.ice.predix.io/sample8
Manager username= sample5-smokeuser / Pa55w0rd
Browser - Google chrome 
Steps-
Steps-
1. Login to application with above credentials
2. Navigate to AViD chart ENTERPRISE > AViD chart SITE > AViD chart SEGMENT > AViD chart Asset > AViD chart Asset Child03 
3. Select Polar from the Chart selector 
4. Search for tag "BR1" > Add an Amp and PH tag to plot a Polar chart  
5. Copy paste a date in the date range picker

Actual - There are a bunch of console errors (screenshot attached)
Expected - User should be able to copy paste a date in Input form fields

![screen shot 2016-11-29 at 2 30 58 pm](https://cloud.githubusercontent.com/assets/19846747/20731860/059ecaa2-b641-11e6-80cf-da78772be2ef.png)

**Comment by benoitjchevalier** [comment]
I don't think copy/paste was officially supported due to the fact that we couldn't get it work across all browsers, we might still fix that if we find time but do not rely on this feature working all the time (IE)
