### ISSUE TITLE
Add limits after first selection

### ISSUE THREAD

**Issue by konraifen88** [predixdesignsystem/px-rangepicker#45]
It would be a great feature if we would be able to limit the maximum date after the first selection is made.

**Example**:
We have set a maximum range of seven days. 
The user taps the 25.08.2017 as first date, so the allowed range for the second date should be set from 18.08.2017 to 01.09.2017.

**Comment by sebastianroming** [comment]
This is exactly what I initially meant in #20 

The user ist just allowed to select a date range of 7 (or X) days, no matter when start or end date is set, but he shouldn't be able to select 8 (or X+1) days or more (X+n).

As you marked it with the enhancement label, is there any roadmap when you will implement it?

**Comment by sebastianroming** [comment]
@Menkhaus-ge any updates on this?

**Comment by katemenkhaus** [comment]
As of right now no. It is in our backlog but I am unsure if it will make it into our Q4 plan. I should know within the next couple of weeks. If it does make it in though it probably wouldn't be implemented till the end of Q4.

**Comment by katemenkhaus** [comment]
Right now this feature is still in the backlog. It will not be worked on this release. 
If more people want this feature please thumbs up the issue and it will be prioritized accordingly in the future.

**Comment by sebastianroming** [comment]
@katemenkhaus Is there anything planned to implement that feature by now? Or still in backlog?

**Comment by kcsoukup** [comment]
Hey... can you please get my email out of the Predix threads? I haven’t worked for GE since Aug 2017.

Thanks!
--
Ken C. Soukup, C|EH
M: 804.313.7199
 
GPG/PGP: 42EC C120 312D 2C7C B526  225E 6CC9 9DD9 FAF7 4B8B

**Comment by gknor** [comment]
Same for me. I've leave GE and I'm not interested in predix any more. And I don't know how to turn off those notifications.
Best regards
Grzegorz

**Comment by Wjonca** [comment]
Exactly. I am not working in GE anymore. I am not interesting in Predix.
Spamming won't change it. Pls turn those msgs off!

Regards
Włodzimierz


Śr., 14.03.2018, 12:47 użytkownik Grzegorz Knor <notifications@github.com>
napisał:

**Comment by sebastianroming** [comment]
@Wjonca @gknor @kcsoukup Neither this is a problem of GE nor Predix nor GitHub. You subscribed for the [https://github.com/predixdesignsystem/px-rangepicker](predixdesignsystem/px-rangepicker) or the predixdesignsystem organization, so you get notifications. Just click `unsubscribe` on the right side of this page, and you won't get notifications for this issue anymore.

Otherwise please unsubscribe from the repository or the organization. How to do is described in https://help.github.com. 

Thanks for **NOT SPAMMING** this thread anymore as this is an issue tracker and not a mailing list. Back to topic.

**Comment by mdwragg** [comment]
Well said @sebastianroming! Thanks :-)

**Comment by katemenkhaus** [comment]
@sebastianroming The feature is still in the backlog. We've needed to work on other features that have had a higher demand. If this is something vital to your team, we can provide guidance/feedback on a PR for this feature.

**Comment by sebastianroming** [comment]
@katemenkhaus sure, yes. Why not :-) Any help for a PR would be appreciated.

**Comment by sebastianroming** [comment]
Still relevant. Any updates on this, @katemenkhaus ?
