### ISSUE TITLE
px-rangepicker with angularjs IE11 - NOT BEING RENDERED! issue

### ISSUE THREAD

**Issue by HackPoint** [predixdesignsystem/px-rangepicker#69]
Hi,
I have tried to use the component within our application,
And it's works fine in Chrome and FF, but in IE11 it doesn't shown

My code of usage:
```
<px-rangepicker
	id="rangePicker"
	automation-id="range-picker"
	resources="{{vm.localeResources}}"
	block-future-dates
	hide-presets
	show-buttons
	date-format="MM/DD/YYYY"
	time-format="HH:mm:ss"
	time-zone="utc"
	show-time-zone="abbreviatedText">
</px-rangepicker>

```

Rendered Result:
```
<px-rangepicker id="rangePicker" show-time-zone="abbreviatedText" time-zone="Asia/Jerusalem" time-format="HH:mm:ss" date-format="MM/DD/YYYY" show-buttons="" hide-presets="" block-future-dates="" resources="{{some rendered json}}" automation-id="range-picker">
</px-rangepicker>
```
As its seems that it doesn't get rendered in IE11, I'm from predix.io team.

Please help to resolve this issue ASAP.

Thanks

**Comment by mdwragg** [comment]
Hi, it’s working fine for us. Can you give us a distilled example we can use to recreate (as per the issue template)?

I take it you’re transpiling for IE?

**Comment by budsalvetti** [comment]
are you loading the polyfill javascript for web compents... because IE needs the polyfill to run polymer.

**Comment by HackPoint** [comment]
@mdwragg it’s a dumb response to say it’s working for us. Every polyfil is loaded. And you have a huge mess with bower! It’s redundant and depricated manager. Please give me instructions to remove it or I will open a critical bug on you in Rally.

**Comment by mdwragg** [comment]
I already got your unedited threatening original response. Locking and closing as that is unacceptable.
